
server:
  port: 8080

spring:
  application:
    name: cheeseballoon
#  datasource:
#    url: jdbc:mariadb://localhost:3306/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: root
#    password: root
#    driver-class-name: org.mariadb.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: kafka-demo
      enable-auto-commit: true
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1000
    template:
      default-topic: kafka-demo



logging:
  level:
    org:
      hibernate: info